# get_proof_data_zkvm_input panics if chain_id=1 and l1_inclusion=true

[`get_proof_data_zkvm_input`](https://github.com/sherlock-audit/2025-07-malda-pyk/blob/51c3a8231a37b622235151254a21cebbc1fa78e1/malda-zk-coprocessor/malda_rs/src/viewcalls.rs#L800)
prepares input data for the ZKVM proof data queries. However, the function
panics when `chain_id=ETHEREUM_CHAIN_ID` and `l1_inclusion=true`.

## Root Cause

When the `get_proof_data_zkvm_input` is called with `chain_id=ETHEREUM_CHAIN_ID`
and `l1_inclusion=true`, it reach the following code branch:

```rust
pub async fn get_env_input_for_l1_inclusion_and_l2_block_number(
    chain_id: u64, // ETHEREUM_CHAIN_ID
    // ...
) -> (Option<EvmInput<EthEvmFactory>>, Option<u64>) {
    if !l1_inclusion {
        // ...
    } else {
        // ...
        if is_opstack_chain(chain_id) {
            // ...
        } else if is_linea_chain(chain_id) {
            // ...
        } else {
            // THIS PANIC IS ALWAYS TRIGGERED FOR ETHEREUM
            panic!(
                "L1 Inclusion only supported for Optimism, Base, Linea and their Sepolia variants"
            );
        }
    }
}
```

I have provided the test case in the PoC section below.

## Internal Pre-conditions

No internal pre-conditions are required.

## External Pre-conditions

No external pre-conditions are required.

## Attack Path

This is not an attack.

## Impact

It completely breaks a core self-sequencing feature described in the
architecture.

## PoC

Add the following test case in `malda-zk-coprocessor/malda_rs/src/viewcalls.rs`:

```rust
#[cfg(test)]
mod tests {
    use super::*;

    /// @custom:property ZK09
    #[tokio::test]
    #[should_panic(
        expected = "L1 Inclusion only supported for Optimism, Base, Linea and their Sepolia variants"
    )]
    async fn test_zk09_ethereum_l1_inclusion() {
        let users = Vec::from([Address::random()]);
        let markets = Vec::from([Address::random()]);
        let chain_id = ETHEREUM_CHAIN_ID;
        let target_chain_ids = Vec::from([LINEA_CHAIN_ID]);
        let l1_inclusion = true;
        let fallback = false;

        // TODO(pyk): what happen when l1_inclusion=false?

        get_proof_data_zkvm_input(
            users,
            markets,
            target_chain_ids,
            chain_id,
            l1_inclusion,
            fallback,
        )
        .await;
    }
}
```

Use the following `.env`:

```rust
RPC_URL_ETHEREUM=https://eth.merkle.io
RPC_URL_ETHEREUM_FALLBACK=https://eth.merkle.io

RPC_URL_OPTIMISM=https://mainnet.optimism.io
RPC_URL_OPTIMISM_FALLBACK=https://mainnet.optimism.io
SEQUENCER_REQUEST_OPTIMISM=https://optimism.operationsolarstorm.org/latest
SEQUENCER_REQUEST_OPTIMISM_FALLBACK=https://optimism.operationsolarstorm.org/latest
```

Then run the test:

```shell
cargo test --package malda_rs test_zk09
```

Logs:

```shell
   Compiling malda_rs v0.1.0 (/home/pyk/github/malda-lending-fuzz/crates/malda_rs)
warning: unused import: `sol_types::SolValue`
  --> crates/malda_rs/src/viewcalls.rs:96:47
   |
96 | use alloy::{signers::local::PrivateKeySigner, sol_types::SolValue};
   |                                               ^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `malda_rs` (lib) generated 1 warning (run `cargo fix --lib -p malda_rs` to apply 1 suggestion)
warning: `malda_rs` (lib test) generated 1 warning (1 duplicate)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 3.01s
     Running unittests src/lib.rs (target/debug/deps/malda_rs-d21341e117a8428e)

running 1 test
test viewcalls::tests::test_zk09_ethereum_l1_inclusion - should panic ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 14 filtered out; finished in 7.60s

     Running tests/tests.rs (target/debug/deps/tests-e748a5907664f80a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 14 filtered out; finished in 0.00s
```

## Migitigation

N/A
